---database exploration--

---explore all objects in the database---

select * from INFORMATION_SCHEMA.TABLES

----Explore all columns in the database--
select * from INFORMATION_SCHEMA.COLUMNS


----dimension exploration---

---explore all countries our customers come from.

use DataWarehouseAnalytics


select distinct country from dbo.[gold.dim_customers]


---explore all categories "the major division"


select * from dbo.[gold.dim_products]

select distinct category,subcategory,product_name from dbo.[gold.dim_products] order by 1,2,3


---date exploration---



---find the date of the first and last order---


select min(order_date) as first_order_date,max(order_date) as last_order_date from dbo.[gold.fact_sales]

--how many year of sales are available

select min(order_date) as first_order_date,max(order_date) as last_order_date,
datediff(year,min(order_date),max(order_date)) as order_range_years from dbo.[gold.fact_sales]


---in months

select min(order_date) as first_order_date,max(order_date) as last_order_date,
datediff(month,min(order_date),max(order_date)) as order_range_months from dbo.[gold.fact_sales]

----find the youngest and oldest customer---

select * from [gold.dim_customers]

select min(birthdate) as oldest_customer,max(birthdate) as youngest_customer from [gold.dim_customers] 

----find the youngest and oldest customer with their age---

select min(birthdate) as oldest_customer,datediff(year,min(birthdate),getdate()) as oldest_age,max(birthdate) as youngest_customer,
datediff(year,max(birthdate),getdate()) as youngest_age from [gold.dim_customers]


---measure exploration--

---find the total sales---

select * from [gold.fact_sales]

select sum(sales_amount) as total_sales from [gold.fact_sales]


---find how many items are sold--

select sum(quantity) as total_quantity from [gold.fact_sales]

---find the average selling price--

select avg(price) as avg_selling_price from [gold.fact_sales]

---find the total number of orders--

select count(order_number) as total_order from [gold.fact_sales]

select count(distinct order_number) as distinct_total_order from [gold.fact_sales]


---find the total number of products--

select count(distinct product_key) as total_products from [gold.dim_products]

---find the total number of customers--

select count(customer_key) as total_customers from [gold.dim_customers]


---find the total number of customers that has placed on order--

select count(distinct customer_key) as total_customer from [gold.fact_sales]


----generate a report that shows all key metrics of the business--

select 'Total_sales' as measure_name ,sum(sales_amount) as measure_value from [gold.fact_sales]
union all
select 'total_quantity' as measure_name,sum(quantity) as measure_value from [gold.fact_sales]
union all
select 'avg_selling_price' as measure_name,avg(price) as measure_value from [gold.fact_sales]
union all
select 'distinct_total_order' as measure_name ,count(distinct order_number) as measure_value from [gold.fact_sales]
union all
select 'total_products' as measure_name,count(distinct product_key) as measure_value from [gold.dim_products]
union all
select 'total_customers' as measure_name,count(customer_key) as measure_value from [gold.dim_customers]


---magnititude analysis--

---find the total customers by countries---

select country,count(customer_key) as total_customers from [gold.dim_customers] group by country order by total_customers desc


--find the total customers by gender--

select gender,count(customer_key) as total_customers from [gold.dim_customers] group by gender order by total_customers desc



---find the products by category---

select category,count(product_name) as total_products from [gold.dim_products] group by category order by total_products desc


--what is the average cost in each category--

select category,avg(cost) as avg_cost from [gold.dim_products] group by category order by avg_cost desc


--what is the total revenue generated for each category--

select p.category,sum(s.sales_amount) total_revenue 
from [gold.fact_sales] s left join [gold.dim_products] p
on p.product_key=s.product_key
group by p.category 
order by total_revenue desc


---find total revenue is generated by each customers--

select c.customer_key,c.first_name,c.last_name,sum(s.sales_amount) as total_revenue
from [gold.fact_sales] s left join [gold.dim_customers] c
on c.customer_key=s.customer_key
group by c.customer_key,c.first_name,c.last_name 
order by total_revenue desc

---what is the distribution of sold items across countries--

select c.country,sum(s.quantity) as total_sold_items
from [gold.fact_sales] s left join [gold.dim_customers] c
on c.customer_key=s.customer_key
group by c.country
order by total_sold_items desc


---Ranking analysis--

---which  5 products generate  the highest revenue--

select top 5 p.product_name,sum(s.sales_amount) total_revenue 
from [gold.fact_sales] s left join [gold.dim_products] p
on p.product_key=s.product_key
group by p.product_name 
order by total_revenue desc

---what are the best 5 subcategory generate the highest revenue--

select top 5 p.subcategory,sum(s.sales_amount) total_revenue 
from [gold.fact_sales] s left join [gold.dim_products] p
on p.product_key=s.product_key
group by p.subcategory 
order by total_revenue desc




----what are the 5 worst-performing products in terms of sales---

select top 5 p.product_name,sum(s.sales_amount) total_revenue 
from [gold.fact_sales] s left join [gold.dim_products] p
on p.product_key=s.product_key
group by p.product_name 
order by total_revenue 

---by using row number
select *
from(
     select  p.product_name,sum(s.sales_amount) total_revenue,
     row_number() over(order by sum(s.sales_amount) desc) as rank_products 
     from [gold.fact_sales] s left join [gold.dim_products] p
     on p.product_key=s.product_key
     group by p.product_name)t
where rank_products <= 5







----what are the 5 worst-performing subcategory in terms of sales---

select top 5 p.subcategory,sum(s.sales_amount) total_revenue 
from [gold.fact_sales] s left join [gold.dim_products] p
on p.product_key=s.product_key
group by p.subcategory 
order by total_revenue 


---find the top 10 customers who have generated the highest revenue--


select top 10 c.customer_key,c.first_name,c.last_name,sum(s.sales_amount) as total_revenue
from [gold.fact_sales] s left join [gold.dim_customers] c
on c.customer_key=s.customer_key
group by c.customer_key,c.first_name,c.last_name 
order by total_revenue desc

---the 3 customers with the fewest order placed---

select top 3 c.customer_key,c.first_name,c.last_name,count(distinct order_number) as total_orders
from [gold.fact_sales] s left join [gold.dim_customers] c
on c.customer_key=s.customer_key
group by c.customer_key,c.first_name,c.last_name 
order by total_orders 













